// TODO: replace with real data once the truck-management API is wired up.

export interface TruckAssignment {
  truckNumber: string;
  finalQty: string;
  status: "Assigned" | "Pending" | "In-Transit" | "Delivered";
  transporterName: string;
  transporterLocation: string;
  assignmentType: string;
  driverName: string;
  driverPhone: string;
  maxCapacity: string;
  startDateTime: string;
  startLocation: string;
  destination: string;
}

export interface PendingContractRow {
  id: string;
  date: string;
  dateValue: number;
  seller: string;
  buyer: string;
  cRate: string;
  cRateValue: number;
  cQty: string;
  cQtyValue: number;
  dQty: string;
  dQtyValue: number;
  aQty: string;
  aQtyValue: number;
  pQty: string;
  pQtyValue: number;
  product: string;
  fromDate: string;
  toDate: string;
  deliveryType: string;
  deliverySchedule: string;
  paymentType: string;
  trucks: TruckAssignment[];
}

const partyOptions = [
  { value: "Chatrai - Lakshmi Poultry", label: "Chatrai - Lakshmi Poultry" },
  { value: "Chilakaluripet - Eswar Traders", label: "Chilakaluripet - Eswar Traders" },
  { value: "Miryalguda - Rayapudi Agro", label: "Miryalguda - Rayapudi Agro" },
  { value: "Tadepalligudem - SL Traders", label: "Tadepalligudem - SL Traders" },
  { value: "Mudinepalli - Purnima Feeds", label: "Mudinepalli - Purnima Feeds" },
];

export const sellerOptions = [{ value: "All", label: "All Sellers" }, ...partyOptions];

export const buyerOptions = [{ value: "All", label: "All Buyers" }, ...partyOptions];

export const deliveryScheduleOptions = [
  { value: "All", label: "All Schedules" },
  { value: "Ready Loading", label: "Ready Loading" },
  { value: "Forward contract", label: "Forward Contract" },
  { value: "Specific Days", label: "Specific Days" },
];

export const pendingContracts: PendingContractRow[] = [
  {
    id: "2026-29",
    date: "18/5/2026",
    dateValue: new Date(2026, 4, 18).getTime(),
    seller: "Chatrai - Lakshmi Poultry",
    buyer: "Chilakaluripet - Eswar Traders",
    cRate: "₹23,000",
    cRateValue: 23000,
    cQty: "50 MT",
    cQtyValue: 50,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "40 MT",
    aQtyValue: 40,
    pQty: "10 MT",
    pQtyValue: 10,
    product: "Maize DDGS",
    fromDate: "17/5/2026",
    toDate: "17/5/2026",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Forward contract",
    paymentType: "100% Advance",
    trucks: [
      {
        truckNumber: "TS27C512",
        finalQty: "30 MT",
        status: "Assigned",
        transporterName: "N/A",
        transporterLocation: "Lakshmi Poultry HO, Tanuku Main Road Tanuku Andhra Pradesh 534211",
        assignmentType: "Truck assigned by Transporter",
        driverName: "Ravi Kumar",
        driverPhone: "+91 90140 22331",
        maxCapacity: "30 MT",
        startDateTime: "20-05-2026 12:00 AM",
        startLocation: "Lakshmi Poultry HO, Tanuku Main Road Tanuku Andhra Pradesh 534211",
        destination:
          "6-114, Pedda Ramalayam, Kattubadi Vari Palem, Chilakaluripet, Palnadu, Andhra Pradesh 522616",
      },
      {
        truckNumber: "SDKJJHDSB",
        finalQty: "10 MT",
        status: "Assigned",
        transporterName: "N/A",
        transporterLocation: "Lakshmi Poultry HO, Tanuku Main Road Tanuku Andhra Pradesh 534211",
        assignmentType: "Truck assigned by Transporter",
        driverName: "UJashuva",
        driverPhone: "+91 87978789",
        maxCapacity: "10 MT",
        startDateTime: "20-05-2026 12:00 AM",
        startLocation: "Lakshmi Poultry HO, Tanuku Main Road Tanuku Andhra Pradesh 534211",
        destination:
          "6-114, Pedda ramalayam, Kattubadi vari palem, Chilakaluripet, Palnadu, Andhra Pradesh Chilakaluripet Andhra Pradesh 522616",
      },
    ],
  },
  {
    id: "2026-17",
    date: "30/4/2026",
    dateValue: new Date(2026, 3, 30).getTime(),
    seller: "Chilakaluripet - Eswar Traders",
    buyer: "Tadepalligudem - SL Traders",
    cRate: "₹1,00,000",
    cRateValue: 100000,
    cQty: "200 MT",
    cQtyValue: 200,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "100 MT",
    aQtyValue: 100,
    pQty: "100 MT",
    pQtyValue: 100,
    product: "Rice DDGS",
    fromDate: "-",
    toDate: "-",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [
      {
        truckNumber: "AP16TA9021",
        finalQty: "100 MT",
        status: "Assigned",
        transporterName: "Sri Ganesh Transports",
        transporterLocation: "Chilakaluripet, Andhra Pradesh 522616",
        assignmentType: "Truck assigned by Seller",
        driverName: "Md. Rafi",
        driverPhone: "+91 93910 44521",
        maxCapacity: "100 MT",
        startDateTime: "01-05-2026 09:00 AM",
        startLocation: "Chilakaluripet, Andhra Pradesh 522616",
        destination: "Tadepalligudem, West Godavari, Andhra Pradesh 534101",
      },
    ],
  },
  {
    id: "2026-16",
    date: "29/4/2026",
    dateValue: new Date(2026, 3, 29).getTime(),
    seller: "Chatrai - Lakshmi Poultry",
    buyer: "Tadepalligudem - SL Traders",
    cRate: "₹1,00,000",
    cRateValue: 100000,
    cQty: "100 MT",
    cQtyValue: 100,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "50 MT",
    aQtyValue: 50,
    pQty: "50 MT",
    pQtyValue: 50,
    product: "Soya DOC",
    fromDate: "-",
    toDate: "-",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Ready Loading",
    paymentType: "100% Advance",
    trucks: [
      {
        truckNumber: "TS09FB3345",
        finalQty: "50 MT",
        status: "Assigned",
        transporterName: "N/A",
        transporterLocation: "Chatrai, Andhra Pradesh 522019",
        assignmentType: "Truck assigned by Transporter",
        driverName: "Suresh Reddy",
        driverPhone: "+91 91821 33045",
        maxCapacity: "50 MT",
        startDateTime: "30-04-2026 08:30 AM",
        startLocation: "Chatrai, Andhra Pradesh 522019",
        destination: "Tadepalligudem, West Godavari, Andhra Pradesh 534101",
      },
    ],
  },
  {
    id: "2026-15",
    date: "29/4/2026",
    dateValue: new Date(2026, 3, 29).getTime(),
    seller: "Chilakaluripet - Eswar Traders",
    buyer: "Miryalguda - Rayapudi Agro",
    cRate: "₹25,00,000",
    cRateValue: 2500000,
    cQty: "800 MT",
    cQtyValue: 800,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "800 MT",
    pQtyValue: 800,
    product: "Soya DOC",
    fromDate: "-",
    toDate: "-",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Ready Loading",
    paymentType: "100% Advance",
    trucks: [],
  },
  {
    id: "2026-12",
    date: "3/3/2026",
    dateValue: new Date(2026, 2, 3).getTime(),
    seller: "Miryalguda - Rayapudi Agro",
    buyer: "Mudinepalli - Purnima Feeds",
    cRate: "₹15,400",
    cRateValue: 15400,
    cQty: "500 MT",
    cQtyValue: 500,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "35 MT",
    aQtyValue: 35,
    pQty: "465 MT",
    pQtyValue: 465,
    product: "DORB",
    fromDate: "-",
    toDate: "-",
    deliveryType: "FOR delivery",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [
      {
        truckNumber: "AP07TB6612",
        finalQty: "35 MT",
        status: "Assigned",
        transporterName: "Rayapudi Logistics",
        transporterLocation: "Miryalguda, Telangana 508207",
        assignmentType: "Truck assigned by Seller",
        driverName: "Kishore Babu",
        driverPhone: "+91 96666 12045",
        maxCapacity: "35 MT",
        startDateTime: "02-03-2026 07:00 AM",
        startLocation: "Miryalguda, Telangana 508207",
        destination: "Mudinepalli, Krishna, Andhra Pradesh 521104",
      },
    ],
  },
  {
    id: "2026-10",
    date: "5/2/2026",
    dateValue: new Date(2026, 1, 5).getTime(),
    seller: "Miryalguda - Rayapudi Agro",
    buyer: "Mudinepalli - Purnima Feeds",
    cRate: "₹100",
    cRateValue: 100,
    cQty: "100 MT",
    cQtyValue: 100,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "100 MT",
    pQtyValue: 100,
    product: "Rice DDGS",
    fromDate: "-",
    toDate: "-",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Specific Days",
    paymentType: "Credits",
    trucks: [],
  },
  {
    id: "2026-9",
    date: "1/2/2026",
    dateValue: new Date(2026, 1, 1).getTime(),
    seller: "Tadepalligudem - SL Traders",
    buyer: "Mudinepalli - Purnima Feeds",
    cRate: "₹48,600",
    cRateValue: 48600,
    cQty: "500 MT",
    cQtyValue: 500,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "500 MT",
    pQtyValue: 500,
    product: "Soya DOC",
    fromDate: "-",
    toDate: "-",
    deliveryType: "FOR delivery",
    deliverySchedule: "Specific Days",
    paymentType: "Forward Advance",
    trucks: [],
  },
  {
    id: "2026-8",
    date: "1/2/2026",
    dateValue: new Date(2026, 1, 1).getTime(),
    seller: "Tadepalligudem - SL Traders",
    buyer: "Chatrai - Lakshmi Poultry",
    cRate: "₹25,000",
    cRateValue: 25000,
    cQty: "100 MT",
    cQtyValue: 100,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "100 MT",
    pQtyValue: 100,
    product: "Maize DDGS",
    fromDate: "-",
    toDate: "-",
    deliveryType: "FOR delivery",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [],
  },
  {
    id: "2026-7",
    date: "1/2/2026",
    dateValue: new Date(2026, 1, 1).getTime(),
    seller: "Tadepalligudem - SL Traders",
    buyer: "Chatrai - Lakshmi Poultry",
    cRate: "₹37,000",
    cRateValue: 37000,
    cQty: "250 MT",
    cQtyValue: 250,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "250 MT",
    pQtyValue: 250,
    product: "Soya DOC",
    fromDate: "-",
    toDate: "-",
    deliveryType: "FOR delivery",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [],
  },
  {
    id: "2026-6",
    date: "1/2/2026",
    dateValue: new Date(2026, 1, 1).getTime(),
    seller: "Tadepalligudem - SL Traders",
    buyer: "Chatrai - Lakshmi Poultry",
    cRate: "₹35,000",
    cRateValue: 35000,
    cQty: "100 MT",
    cQtyValue: 100,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "100 MT",
    pQtyValue: 100,
    product: "Rice DDGS",
    fromDate: "-",
    toDate: "-",
    deliveryType: "FOR delivery",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [],
  },
  {
    id: "2026-5",
    date: "28/1/2026",
    dateValue: new Date(2026, 0, 28).getTime(),
    seller: "Mudinepalli - Purnima Feeds",
    buyer: "Chatrai - Lakshmi Poultry",
    cRate: "₹32,000",
    cRateValue: 32000,
    cQty: "150 MT",
    cQtyValue: 150,
    dQty: "0 MT",
    dQtyValue: 0,
    aQty: "0 MT",
    aQtyValue: 0,
    pQty: "150 MT",
    pQtyValue: 150,
    product: "Maize DDGS",
    fromDate: "-",
    toDate: "-",
    deliveryType: "Ex-Loading",
    deliverySchedule: "Ready Loading",
    paymentType: "Credits",
    trucks: [],
  },
];
