import type { Truck } from "./trucks.types";

// TODO: replace with a real trucksApi (RTK Query) once the backend exposes a
// GetAllTrucks summary endpoint. Field shape below follows the payload the
// backend team shared for the truck record.
export const MOCK_TRUCKS: Truck[] = [
  {
    profileId: 1,
    truckNumber: "TRK-1001",
    registrationNumber: "AP09 TC 1234",
    truckType: "Open Body",
    make: "Tata",
    model: "LPT 1613",
    manufactureYear: 2020,
    capacity: 16,
    capacityUnit: "MT",
    fuelType: "Diesel",
    ownershipType: "Owned",
    actionPerformedBy: 1,
  },
  {
    profileId: 2,
    truckNumber: "TRK-1002",
    registrationNumber: "TS07 UD 5678",
    truckType: "Container",
    make: "Ashok Leyland",
    model: "Ecomet 1615",
    manufactureYear: 2021,
    capacity: 15,
    capacityUnit: "MT",
    fuelType: "Diesel",
    ownershipType: "Attached",
    actionPerformedBy: 1,
  },
  {
    profileId: 3,
    truckNumber: "TRK-1003",
    registrationNumber: "KA03 MJ 9012",
    truckType: "Trailer",
    make: "BharatBenz",
    model: "3123R",
    manufactureYear: 2019,
    capacity: 31,
    capacityUnit: "MT",
    fuelType: "Diesel",
    ownershipType: "Leased",
    actionPerformedBy: 1,
  },
  {
    profileId: 4,
    truckNumber: "TRK-1004",
    registrationNumber: "AP16 TB 3456",
    truckType: "Tanker",
    make: "Eicher",
    model: "Pro 3015",
    manufactureYear: 2022,
    capacity: 9,
    capacityUnit: "Tons",
    fuelType: "CNG",
    ownershipType: "Owned",
    actionPerformedBy: 1,
  },
  {
    profileId: 5,
    truckNumber: "TRK-1005",
    registrationNumber: "TS09 UF 7890",
    truckType: "Open Body",
    make: "Mahindra",
    model: "Blazo X 28",
    manufactureYear: 2023,
    capacity: 28,
    capacityUnit: "MT",
    fuelType: "Diesel",
    ownershipType: "Attached",
    actionPerformedBy: 1,
  },
];
