// TODO: replace with real data once the contract-status API is wired up.

export interface ContractStatusRecord {
  contractNumber: string;
  financialYear: string;
  contractDate: string;
  seller: string;
  buyer: string;
  productName: string;
  deliveryType: string;
  contractQuantity: string;
  suppliedQuantity: string;
  invoiceRatePerMT: string;
  gstPercent: string;
  invoiceNetRatePerMT: string;
  contractValue: string;
  totalInvoicesAmount: string;
  totalInvoicesNetAmount: string;
  paidAmount: string;
  deliveryCompleted: boolean;
  paymentDone: boolean;
  contractClosed: boolean;
}

export const financialYearOptions = [
  { value: "2021-2022", label: "2021-2022" },
  { value: "2022-2023", label: "2022-2023" },
  { value: "2023-2024", label: "2023-2024" },
  { value: "2024-2025", label: "2024-2025" },
  { value: "2025-2026", label: "2025-2026" },
];

export const contractStatusRecords: ContractStatusRecord[] = [
  {
    contractNumber: "2431",
    financialYear: "2023-2024",
    contractDate: "24-12-2025",
    seller: "FairSquare Trading Pvt Ltd - Pune",
    buyer: "Srinivasa Traders - Vijayawada",
    productName: "Soya DOC",
    deliveryType: "Ex - Loading",
    contractQuantity: "3000 MT",
    suppliedQuantity: "2000 MT",
    invoiceRatePerMT: "₹43,200",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹45,360",
    contractValue: "₹13,60,800",
    totalInvoicesAmount: "₹13,60,800",
    totalInvoicesNetAmount: "₹13,60,800",
    paidAmount: "₹13,60,800",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: true,
  },
  {
    contractNumber: "2458",
    financialYear: "2023-2024",
    contractDate: "02-01-2026",
    seller: "Chatrai - Lakshmi Poultry",
    buyer: "Tadepalligudem - SL Traders",
    productName: "Maize DDGS",
    deliveryType: "FOR Delivery",
    contractQuantity: "1500 MT",
    suppliedQuantity: "900 MT",
    invoiceRatePerMT: "₹28,500",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹29,925",
    contractValue: "₹4,27,500",
    totalInvoicesAmount: "₹2,56,500",
    totalInvoicesNetAmount: "₹2,69,325",
    paidAmount: "₹1,80,000",
    deliveryCompleted: false,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "2210",
    financialYear: "2022-2023",
    contractDate: "18-08-2024",
    seller: "Miryalguda - Rayapudi Agro",
    buyer: "Chilakaluripet - Eswar Traders",
    productName: "Rice DDGS",
    deliveryType: "Ex - Loading",
    contractQuantity: "2200 MT",
    suppliedQuantity: "2200 MT",
    invoiceRatePerMT: "₹31,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹32,550",
    contractValue: "₹68,20,000",
    totalInvoicesAmount: "₹68,20,000",
    totalInvoicesNetAmount: "₹71,61,000",
    paidAmount: "₹71,61,000",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: false,
  },
  {
    contractNumber: "3840",
    financialYear: "2024-2025",
    contractDate: "15-01-2025",
    seller: "Ankur Animal Feeds",
    buyer: "Sai Feeds Pvt Ltd",
    productName: "Wheat",
    deliveryType: "Ex - Loading",
    contractQuantity: "500 MT",
    suppliedQuantity: "500 MT",
    invoiceRatePerMT: "₹25,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹26,250",
    contractValue: "₹1,25,00,000",
    totalInvoicesAmount: "₹1,25,00,000",
    totalInvoicesNetAmount: "₹1,31,25,000",
    paidAmount: "₹1,31,25,000",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: false,
  },
  {
    contractNumber: "3841",
    financialYear: "2024-2025",
    contractDate: "16-01-2025",
    seller: "Green Valley Dairy",
    buyer: "Blue Aqua Farms",
    productName: "Rice",
    deliveryType: "FOR Delivery",
    contractQuantity: "750 MT",
    suppliedQuantity: "400 MT",
    invoiceRatePerMT: "₹30,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹31,500",
    contractValue: "₹2,25,00,000",
    totalInvoicesAmount: "₹1,20,00,000",
    totalInvoicesNetAmount: "₹1,26,00,000",
    paidAmount: "₹1,00,00,000",
    deliveryCompleted: false,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "3842",
    financialYear: "2024-2025",
    contractDate: "17-01-2025",
    seller: "Sai Feeds Pvt Ltd",
    buyer: "Green Valley Dairy",
    productName: "Corn",
    deliveryType: "Ex - Loading",
    contractQuantity: "600 MT",
    suppliedQuantity: "600 MT",
    invoiceRatePerMT: "₹28,500",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹29,925",
    contractValue: "₹1,71,00,000",
    totalInvoicesAmount: "₹1,71,00,000",
    totalInvoicesNetAmount: "₹1,79,55,000",
    paidAmount: "₹90,00,000",
    deliveryCompleted: true,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "3843",
    financialYear: "2024-2025",
    contractDate: "18-01-2025",
    seller: "Ankur Animal Feeds",
    buyer: "Blue Aqua Farms",
    productName: "Maize",
    deliveryType: "Ex - Loading",
    contractQuantity: "850 MT",
    suppliedQuantity: "850 MT",
    invoiceRatePerMT: "₹26,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹27,300",
    contractValue: "₹2,21,00,000",
    totalInvoicesAmount: "₹2,21,00,000",
    totalInvoicesNetAmount: "₹2,32,05,000",
    paidAmount: "₹2,32,05,000",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: false,
  },
  {
    contractNumber: "3844",
    financialYear: "2024-2025",
    contractDate: "19-01-2025",
    seller: "Green Valley Dairy",
    buyer: "Sai Feeds Pvt Ltd",
    productName: "Soybean",
    deliveryType: "FOR Delivery",
    contractQuantity: "400 MT",
    suppliedQuantity: "250 MT",
    invoiceRatePerMT: "₹32,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹33,600",
    contractValue: "₹1,28,00,000",
    totalInvoicesAmount: "₹80,00,000",
    totalInvoicesNetAmount: "₹84,00,000",
    paidAmount: "₹60,00,000",
    deliveryCompleted: false,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "3845",
    financialYear: "2024-2025",
    contractDate: "21-01-2025",
    seller: "Ankur Animal Feeds",
    buyer: "Green Valley Dairy",
    productName: "Sunflower",
    deliveryType: "Ex - Loading",
    contractQuantity: "700 MT",
    suppliedQuantity: "700 MT",
    invoiceRatePerMT: "₹24,500",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹25,725",
    contractValue: "₹1,71,50,000",
    totalInvoicesAmount: "₹1,71,50,000",
    totalInvoicesNetAmount: "₹1,80,07,500",
    paidAmount: "₹1,80,07,500",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: false,
  },
  {
    contractNumber: "3846",
    financialYear: "2024-2025",
    contractDate: "22-01-2025",
    seller: "Sai Feeds Pvt Ltd",
    buyer: "Blue Aqua Farms",
    productName: "Barley",
    deliveryType: "FOR Delivery",
    contractQuantity: "550 MT",
    suppliedQuantity: "550 MT",
    invoiceRatePerMT: "₹27,500",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹28,875",
    contractValue: "₹1,51,25,000",
    totalInvoicesAmount: "₹1,51,25,000",
    totalInvoicesNetAmount: "₹1,58,81,250",
    paidAmount: "₹1,20,00,000",
    deliveryCompleted: true,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "3847",
    financialYear: "2024-2025",
    contractDate: "23-01-2025",
    seller: "Ankur Animal Feeds",
    buyer: "Sai Feeds Pvt Ltd",
    productName: "Bajra",
    deliveryType: "Ex - Loading",
    contractQuantity: "300 MT",
    suppliedQuantity: "150 MT",
    invoiceRatePerMT: "₹23,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹24,150",
    contractValue: "₹69,00,000",
    totalInvoicesAmount: "₹34,50,000",
    totalInvoicesNetAmount: "₹36,22,500",
    paidAmount: "₹20,00,000",
    deliveryCompleted: false,
    paymentDone: false,
    contractClosed: false,
  },
  {
    contractNumber: "3848",
    financialYear: "2024-2025",
    contractDate: "24-01-2025",
    seller: "Green Valley Dairy",
    buyer: "Blue Aqua Farms",
    productName: "Jowar",
    deliveryType: "FOR Delivery",
    contractQuantity: "450 MT",
    suppliedQuantity: "450 MT",
    invoiceRatePerMT: "₹29,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹30,450",
    contractValue: "₹1,30,50,000",
    totalInvoicesAmount: "₹1,30,50,000",
    totalInvoicesNetAmount: "₹1,37,02,500",
    paidAmount: "₹1,37,02,500",
    deliveryCompleted: true,
    paymentDone: true,
    contractClosed: false,
  },
  {
    contractNumber: "3849",
    financialYear: "2024-2025",
    contractDate: "25-01-2025",
    seller: "Sai Feeds Pvt Ltd",
    buyer: "Green Valley Dairy",
    productName: "Cotton Seed",
    deliveryType: "Ex - Loading",
    contractQuantity: "900 MT",
    suppliedQuantity: "900 MT",
    invoiceRatePerMT: "₹21,000",
    gstPercent: "5%",
    invoiceNetRatePerMT: "₹22,050",
    contractValue: "₹1,89,00,000",
    totalInvoicesAmount: "₹1,89,00,000",
    totalInvoicesNetAmount: "₹1,98,45,000",
    paidAmount: "₹1,50,00,000",
    deliveryCompleted: true,
    paymentDone: false,
    contractClosed: false,
  },
];

// ============================================================
// "Get Contracts" lookup drawer (opened from the Contract Number link button)
// ============================================================
export interface GetContractsRow {
  sNo: number;
  cDate: string;
  contractNumber: string;
  buyer: string;
  seller: string;
  product: string;
  totalMTs: number;
  rateMT: number;
}

export const drawerSellerOptions = [
  { value: "ankur-animal-feeds", label: "Ankur Animal Feeds" },
  { value: "green-valley-dairy", label: "Green Valley Dairy" },
  { value: "sai-feeds-pvt-ltd", label: "Sai Feeds Pvt Ltd" },
];

export const drawerBuyerOptions = [
  { value: "sai-feeds-pvt-ltd", label: "Sai Feeds Pvt Ltd" },
  { value: "blue-aqua-farms", label: "Blue Aqua Farms" },
  { value: "green-valley-dairy", label: "Green Valley Dairy" },
];

export const getContractsRows: GetContractsRow[] = [
  {
    sNo: 1,
    cDate: "15-01-2025",
    contractNumber: "3840",
    buyer: "Sai Feeds Pvt Ltd",
    seller: "Ankur Animal Feeds",
    product: "Wheat",
    totalMTs: 500,
    rateMT: 25000,
  },
  {
    sNo: 2,
    cDate: "16-01-2025",
    contractNumber: "3841",
    buyer: "Blue Aqua Farms",
    seller: "Green Valley Dairy",
    product: "Rice",
    totalMTs: 750,
    rateMT: 30000,
  },
  {
    sNo: 3,
    cDate: "17-01-2025",
    contractNumber: "3842",
    buyer: "Green Valley Dairy",
    seller: "Sai Feeds Pvt Ltd",
    product: "Corn",
    totalMTs: 600,
    rateMT: 28500,
  },
  {
    sNo: 4,
    cDate: "18-01-2025",
    contractNumber: "3843",
    buyer: "Blue Aqua Farms",
    seller: "Ankur Animal Feeds",
    product: "Maize",
    totalMTs: 850,
    rateMT: 26000,
  },
  {
    sNo: 5,
    cDate: "19-01-2025",
    contractNumber: "3844",
    buyer: "Sai Feeds Pvt Ltd",
    seller: "Green Valley Dairy",
    product: "Soybean",
    totalMTs: 400,
    rateMT: 32000,
  },
  {
    sNo: 6,
    cDate: "21-01-2025",
    contractNumber: "3845",
    buyer: "Green Valley Dairy",
    seller: "Ankur Animal Feeds",
    product: "Sunflower",
    totalMTs: 700,
    rateMT: 24500,
  },
  {
    sNo: 7,
    cDate: "22-01-2025",
    contractNumber: "3846",
    buyer: "Blue Aqua Farms",
    seller: "Sai Feeds Pvt Ltd",
    product: "Barley",
    totalMTs: 550,
    rateMT: 27500,
  },
  {
    sNo: 8,
    cDate: "23-01-2025",
    contractNumber: "3847",
    buyer: "Sai Feeds Pvt Ltd",
    seller: "Ankur Animal Feeds",
    product: "Bajra",
    totalMTs: 300,
    rateMT: 23000,
  },
  {
    sNo: 9,
    cDate: "24-01-2025",
    contractNumber: "3848",
    buyer: "Blue Aqua Farms",
    seller: "Green Valley Dairy",
    product: "Jowar",
    totalMTs: 450,
    rateMT: 29000,
  },
  {
    sNo: 10,
    cDate: "25-01-2025",
    contractNumber: "3849",
    buyer: "Green Valley Dairy",
    seller: "Sai Feeds Pvt Ltd",
    product: "Cotton Seed",
    totalMTs: 900,
    rateMT: 21000,
  },
];
